add plugin settings category
replugged-org/replugged pull request #155
Opened 2022-08-26 12:54 UTC by 12944qwerty

Adds the plugin category

Untested as I just coded this on my chromebook

2022-08-26 14:31 UTC, asportnoy requested changes
- General Settings, Plugins, Themes, and Quick CSS are all showing in the plugins settings section
- Make the section header an i18n key and name it "Plugin Settings" instead of just "Plugins"
- Sort by the plugin name instead of ID; some of them are visually out-of-order since the ID is different from the name.

2022-08-26 23:36 UTC, lleyton requested changes

2022-08-26 23:36 UTC, lleyton commented on src/Powercord/coremods/settings/index.js
> +        .sort((a, b) => powercord.api.settings.tabs[a].label < powercord.api.settings.tabs[b].label)
let's use [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) instead

2022-08-27 01:15 UTC, asportnoy requested changes

2022-08-27 01:15 UTC, asportnoy commented on src/Powercord/coremods/settings/index.js
> +        .filter(s => ['pc-moduleManager-themes', 'pc-moduleManager-css', 'pc-moduleManager-plugins', 'pc-general', 'pc-updater'].indexOf(s) >= 0)
Make this array a variable to avoid repetition 
Use `Array.includes` instead of `indexOf`

2022-08-27 14:56 UTC, asportnoy commented
Also, the linter needs to be run

2022-08-27 15:39 UTC, asportnoy approved these changes

2022-08-27 15:45 UTC, Vendicated approved these changes

2022-08-27 16:24 UTC, merged