Make some strings unhardcoded so they can be translated
replugged-org/replugged pull request #164
Opened 2022-08-29 10:07 UTC by Abstructor

Title

2022-08-29 22:50 UTC, lexisother commented
???

2022-08-29 23:13 UTC, Abstructor commented
Whoops. I might have accidentally closed this PR while checking on it

2022-08-30 00:40 UTC, asportnoy requested changes
There are some more strings that should be added to i18n as well (only including ones in settings and updater for now)
https://github.com/replugged-org/replugged/blob/c8089068d15d2cffd19248a14ce3356877aa535b/src/Powercord/coremods/settings/components/ErrorBoundary.jsx#L66-L72
https://github.com/replugged-org/replugged/blob/c8089068d15d2cffd19248a14ce3356877aa535b/src/Powercord/coremods/settings/components/GeneralSettings/index.jsx#L37
https://github.com/replugged-org/replugged/blob/c8089068d15d2cffd19248a14ce3356877aa535b/src/Powercord/coremods/updater/index.js#L369
https://github.com/replugged-org/replugged/blob/c8089068d15d2cffd19248a14ce3356877aa535b/src/Powercord/coremods/updater/components/Settings.jsx#L350-L433
https://github.com/replugged-org/replugged/blob/c8089068d15d2cffd19248a14ce3356877aa535b/src/Powercord/coremods/updater/components/Settings.jsx#L439

2022-08-30 00:40 UTC, asportnoy commented on src/Powercord/coremods/updater/index.js
> +    label: Messages.REPLUGGED_UPDATES_UPDATER, // Note to self: add this string to i18n last :^)
```suggestion
    label: Messages.REPLUGGED_UPDATES_UPDATER,
```

2022-08-30 03:21 UTC, Abstructor commented on src/Powercord/coremods/updater/index.js
> +    label: Messages.REPLUGGED_UPDATES_UPDATER, // Note to self: add this string to i18n last :^)
Changes resolved.

2022-08-30 03:27 UTC, asportnoy approved these changes
LGTM

2022-08-30 06:23 UTC, lexisother approved these changes
Yop.

2022-08-30 12:48 UTC, 12944qwerty requested changes
Several, if not all, of the badges' tooltips could be included. [coremods/badges](https://github.com/Abstructor/replugged/blob/main/src/Powercord/coremods/badges/index.js#L55-L81)
This [notice](https://github.com/Abstructor/replugged/blob/main/src/Powercord/coremods/notices/index.js#L43) can probably be translated
I think some toasts could also be translated, but not 100% sure if we need to/should. [coremods/routelinks](https://github.com/Abstructor/replugged/blob/main/src/Powercord/coremods/routelinks/index.js)

I've checked most files, but be sure to check the components folder as well just in case.

2022-08-30 18:35 UTC, asportnoy commented
The badges already have translations.

2022-08-31 03:29 UTC, Abstructor commented
Should I make the built in coremods commands descriptions (like this one below) translatable too?
![image](https://i.imgur.com/3nAekEi.png)

2022-08-31 04:35 UTC, Abstructor commented
And strings like these are pretty much impossible to create an i18n string for since they have a variable in the middle of the string
![image](https://i.imgur.com/ypMsKG9.png)

2022-08-31 05:06 UTC, asportnoy commented
```json
MY_STRING: "Something {varname}"
```

```js
Messages.MY_STRING.format({
  varname: "some value"
});
```

2022-08-31 05:23 UTC, Abstructor commented
Ah, thank you

2022-08-31 07:30 UTC, Abstructor commented
That should be it I think.

2022-08-31 08:01 UTC, Abstructor commented
Done

2022-08-31 16:29 UTC, lleyton approved these changes
Looks good with me, I'll need local validation though

2022-08-31 21:09 UTC, 12944qwerty approved these changes

2022-08-31 21:11 UTC, merged