Plaintext Patching closes #181
replugged-org/replugged pull request #201
Opened 2022-09-22 07:40 UTC by lleyton

Adds a new method (patchPlaintext) on the `powercord/webpack` API, which allows for directly patching module source code as plaintext.

Closes #181

2022-09-23 17:16 UTC, lexisother requested changes
Plugins load way after Webpack is done loading. This means that trying to patch an already required Webpack module will not work. (as it already exists in the require cache)
Instead of going at it in this manner, we should probably run our stuff in renderer.

2022-09-24 20:52 UTC, asportnoy reviewed
Can you give an example of how this is used and what it can do that we couldn't do previously?

2022-09-24 22:25 UTC, lexisother commented
Patch unfetchable code, constants, local vars, etc.

2022-11-01 23:28 UTC, asportnoy commented
No longer relevant

2022-11-01 23:28 UTC, closed without merging