Fix all ESLint issues
replugged-org/replugged pull request #212
Opened 2022-10-21 21:06 UTC by lexisother

Does as it says on the tin.

2022-10-21 21:07 UTC, lleyton commented
> merge 107 commits into [main](https://github.com/replugged-org/replugged)

uuuh, I don't think that's that you want, lexi-cat

2022-10-21 21:08 UTC, lexisother commented
silence, wench!

2022-10-22 03:21 UTC, lleyton approved these changes
Ready.

2022-10-22 03:36 UTC, asportnoy requested changes
Pretty good for the most part, just some minor things here and there.

2022-10-22 03:36 UTC, asportnoy commented on scripts/inject/index.ts
> +        } catch (_e) {}
Let's just remove the catch argument for all of these cases (not gonna comment on each one).
```suggestion
        } catch {}
```

2022-10-22 03:36 UTC, asportnoy commented on src/globals.d.ts
> +    React: typeof import("react");
Add import `import type React from "react";` above and change this to `React: typeof React;`

2022-10-22 03:36 UTC, asportnoy commented on src/preload.ts
> +webFrame.executeJavaScript(renderer).then((_r) => {});
Why do you need the promise here? Might be good to add a comment explaining.

2022-10-22 03:36 UTC, asportnoy commented on src/types/addon.ts
>    discord_id: z.string(),
Should we switch this parameter to camel case instead?

2022-10-22 04:40 UTC, asportnoy approved these changes
LGTM!

2022-10-22 04:42 UTC, lleyton commented
:leaSpin:

2022-10-22 04:42 UTC, merged