Fix injection Script
replugged-org/replugged pull request #225
Opened 2022-11-18 23:45 UTC by ShadiestGoat

This is low priority PR only affects the injection script. 

All it does is removes the use of `process.argv` in favor of the use of a filtered array. This allows you to hardcode indecies like 2 or 3 without the need to worry about cmd flags & switches

2022-11-18 23:46 UTC, ShadiestGoat commented
*Renamed PR because it doesn't *fix* the script, it just *changes* it

2022-12-11 04:20 UTC, asportnoy requested changes
Please run the linter and re-request my review.

2022-12-12 09:48 UTC, ShadiestGoat commented
Alright seems to to be linted & prettier-ed

2022-12-14 05:42 UTC, asportnoy approved these changes

2022-12-14 05:42 UTC, merged