Adds shebang to replugged executable
replugged-org/replugged pull request #430
Opened 2023-03-17 11:58 UTC by Allvaa

The executable failed to run on Linux when I tried to run a command to build plugin.
![image](https://user-images.githubusercontent.com/52526068/225896381-7caa693e-96fe-49c7-9ee8-519049e1303f.png)

Adding a shebang line fixed the problem. Now I can run the command with no error.
![image](https://user-images.githubusercontent.com/52526068/225897268-1d84785c-5346-4394-ba5e-eb2d55c8e78f.png)

2023-03-17 12:41 UTC, asportnoy commented
I think there was a reason we removed this. Let me see if there is another workaround.

2023-03-17 12:41 UTC, asportnoy requested changes
Blocking merge for now

2023-03-17 14:34 UTC, Allvaa commented
> [a6c7599](https://github.com/replugged-org/replugged/commit/a6c75993653c46eca80a281e786078733daf8baa)

Anyway why was it not needed?
Also I think issues in the editor are relative, I don't see any issue in my editor with shebang

2023-03-18 03:47 UTC, asportnoy approved these changes
I think editor issues were the initial issue and it worked without it (still does for me at least). But it doesn't seem to be having issues now so I'll approve.

2023-03-18 03:47 UTC, merged