Auto update checking
replugged-org/replugged pull request #467
Opened 2023-06-03 03:33 UTC by asportnoy

Automatically check for addon and Replugged updates. Default / minimum interval is 10 minutes and is configurable in updater settings. Only store addons will be checked for updates due to GitHub's rate limits. A announcement/notice will be shown at the top of your screen when an update is available

This PR actually implements the notices API. While the API technically did change, it was never actually implemented, nor documented anywhere, so I wouldn't consider this a breaking change.

To test, use this asar: https://github.com/asportnoy/store-updater-demo/releases/download/v1.0.1/dev.albertp.StoreUpdaterDemo.asar
To skip the 10m wait for testing, run `(await replugged.settings.init('dev.replugged.Updater.State')).delete("lastChecked")`. It will then trigger on the next interval (<1m).

Closes #379.

2023-06-04 11:51 UTC, FedeIlLeone requested changes

2023-06-04 11:51 UTC, FedeIlLeone commented on src/renderer/coremods/notices/index.tsx
> +function Announcement({
Why not use Discord's notice components instead of recreating it?

2023-06-04 13:18 UTC, asportnoy commented on src/types/index.ts
> +  Success = "colorSuccess",
I think it's ok if it's an alias

2023-06-04 14:56 UTC, FedeIlLeone approved these changes

2023-06-07 21:50 UTC, aaronliu0130 commented
could this be merged?

2023-06-07 21:51 UTC, asportnoy commented
We're waiting for more addons to migrate to the store since GitHub addons will not be supported, though we plan to release it within the next week or so.

2023-06-10 03:01 UTC, merged