Auto relaunch
replugged-org/replugged pull request #517
Opened 2023-07-16 10:10 UTC by Tharki-God

automatically close discord and open it back on plug/unplug/replug.

the behavior can be avoided by passing the argument `--no-relaunch`.

2023-07-16 13:08 UTC, asportnoy requested changes

2023-07-16 13:08 UTC, asportnoy commented on scripts/inject/index.mts
> +      if (noRelaunch) {
This should be moved to a function instead of repeated twice

2023-07-16 13:10 UTC, asportnoy requested changes

2023-07-16 13:10 UTC, asportnoy commented on scripts/inject/util.mts
> +    const checkInterval = setInterval(() => {
Add some timeout here in case it never quits so it won't hang indefinitely

2023-07-19 18:12 UTC, asportnoy requested changes

2023-07-19 18:12 UTC, asportnoy commented on scripts/inject/injector.mts
> +          });
Instead of this, run `open -a "Discord Canary"` (or other platform name).

2023-07-21 02:06 UTC, asportnoy commented on scripts/inject/injector.mts
> +          });
exec

2023-08-23 00:51 UTC, asportnoy requested changes
Requested changes have not been made

2023-09-24 06:28 UTC, Tharki-God commented
also made it so that if Discord wasn't open before then don't launch it after.

2024-07-12 13:09 UTC, FedeIlLeone approved these changes

2025-02-26 05:32 UTC, colin273 approved these changes

2025-02-26 11:37 UTC, merged