a very serious pr
replugged-org/replugged pull request #531
Opened 2023-08-07 23:00 UTC by Tharki-God

removes all line breaks from code in plain text patch. wouldnt break anything since minified codes work fine without line breaks

2023-08-18 18:13 UTC, lexisother submitted a review, later dismissed

2023-08-19 01:20 UTC, asportnoy approved these changes

2023-08-19 01:24 UTC, asportnoy requested changes
This needs to be updated to handle literal `\n`s in the code

2023-08-19 01:39 UTC, colin273 requested changes
Why would we modify Discord's code beyond what we already do? This makes assumptions about Discord's minifier that I would prefer to avoid, namely that newline characters will never appear in, say, a template string. Perhaps this is true, but if it ever stops being true, I don't think this is something we should have to go back and fix.

I would prefer that developers account for possible white space in their regexes as JavaScript syntax would logically allow, if they're willing to attempt plaintext patches at all.

2023-08-19 08:06 UTC, lexisother commented
If you as a plugin developer come across an instance where a newline in code is messing with your plaintext patch (e.g. when using `.` to target characters), move to `[^]` and manually account for other instances of whitespace.

2023-08-19 08:06 UTC, closed without merging