Quickcss improvements
replugged-org/replugged pull request #557
Opened 2023-09-20 17:16 UTC by 12944qwerty

Makes the editor a fixed size and popoutable. Still have to implement settings and pin to front button.

2023-09-22 18:20 UTC, FedeIlLeone requested changes

2023-09-22 18:20 UTC, FedeIlLeone commented on src/renderer/coremods/settings/pages/QuickCSS.tsx
> +          button="Close Popout"
i18n. You can use POPOUT_RETURN.

2023-09-22 18:20 UTC, FedeIlLeone commented on src/renderer/coremods/settings/pages/QuickCSS.tsx
> +                        <DnDProvider windowKey="DISCORD_REPLUGGED_QUICKCSS">
Pass a `title` prop to set the window title, or else it will be undefined.

2023-09-22 18:20 UTC, FedeIlLeone commented on src/renderer/coremods/settings/pages/QuickCSS.tsx
> +const DnDProvider = webpack.getBySource(
To be precise, do not confuse the two components, which are different (DragAndDropProvider vs PopoutWindow)
```suggestion
const PopoutWindow = webpack.getBySource(
```

2023-09-22 18:20 UTC, FedeIlLeone commented on src/renderer/coremods/settings/pages/QuickCSS.tsx
> +// eslint-disable-next-line @typescript-eslint/non-nullable-type-assertion-style
All these comments to disable the rules are useless. Instead use the `!` assertion, or even better check later if it's undefined or not.

2023-09-22 18:20 UTC, FedeIlLeone commented on src/renderer/coremods/settings/pages/QuickCSS.tsx
> +const openPopout = webpack.getFunctionBySource(PopoutModule, "POPOUT_WINDOW_OPEN") as (
Type generics are a thing with these webpack functions. Use them.

2023-09-22 18:20 UTC, FedeIlLeone commented on src/renderer/coremods/settings/pages/QuickCSS.tsx
> +  render: ReactComponent<unknown>,
I completely deleted the `ReactComponent` type quite some time ago for obvious reasons. You could pass any prop without type checking. Instead create a new type with the correct types.

2024-10-26 04:14 UTC, 12944qwerty commented
Closing in favor of #652

2024-10-26 04:14 UTC, closed without merging