Slash command api bug fix and features
replugged-org/replugged pull request #559
Opened 2023-09-24 06:11 UTC by Tharki-God

fixes the bug of Clyde becoming replugged after using a command with an ephemeral return message. 

also added handling for sub-commands and sub-command groups... 

well actually the types for it aren't complete and I can't seem to figure out how to type it with Dynamic typing for options, if someone else can do that then it would be great help

2023-09-24 18:31 UTC, FedeIlLeone requested changes

2023-09-24 18:31 UTC, FedeIlLeone commented on src/types/discord.ts
> +  SubCommand = 1,
As the [official Discord doc](https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups) says. Consequently rename all SubCommand to Subcommand.
```suggestion
  Subcommand = 1,
```

2023-09-24 18:31 UTC, FedeIlLeone commented on src/renderer/apis/commands.ts
> +declare class UserClass implements User {
This is not needed. Just define the type of the module that you are waiting for below as `typeof User`.

2023-10-17 23:53 UTC, asportnoy approved these changes

2023-10-18 05:11 UTC, FedeIlLeone approved these changes

2023-10-18 13:03 UTC, merged