Fix unswc even more
replugged-org/replugged pull request #585
Opened 2023-10-28 11:10 UTC by Tharki-God

fixes some coremods and fixes the plain text patch for some coremods not loading due to race conditions or something.
also fixed some errors with plain text patch eval logic and now it logs out the error if any + makes it easy to find patches file in sources tab

2023-10-28 16:24 UTC, asportnoy commented on src/renderer/modules/webpack/patch-load.ts
> +// Intercept he webpack chunk global as soon as Discord creates it
```suggestion
// Intercept the webpack chunk global as soon as Discord creates it
```

2023-10-29 17:14 UTC, FedeIlLeone requested changes

2023-10-29 17:14 UTC, FedeIlLeone commented on src/renderer/coremods/badges/index.tsx
> +  const mod = await waitForProps<{ BadgeSizes: Record<string, string>; default: BadgeMod }>(
```suggestion
  const mod = await waitForProps<{ BadgeSizes: BadgeSizes; default: BadgeMod }>(
```

2023-10-29 17:14 UTC, FedeIlLeone commented on src/renderer/modules/components/Notice.tsx
> -Notice.Types = Types;
Add this back for backwards compatibility

2023-11-02 03:44 UTC, asportnoy approved these changes

2023-11-02 06:15 UTC, FedeIlLeone approved these changes

2023-11-02 06:28 UTC, merged