fixed slash command api
replugged-org/replugged pull request #604
Opened 2024-03-12 23:51 UTC by YofukashiNo

Fixed Slash commands not showing up
Embeded slash command's icon into replugged renderer itself

2024-04-03 23:07 UTC, 12944qwerty approved these changes

2024-04-07 13:50 UTC, FedeIlLeone requested changes
Just this

2024-04-07 13:50 UTC, FedeIlLeone commented on src/renderer/coremods/commands/index.ts
> +        serverVersion: symbol | string;
Can you make a type just for this? This exact record is copied and pasted for almost every function below, resulting in duplicate code.

2024-04-07 19:54 UTC, FedeIlLeone requested changes

2024-04-07 19:54 UTC, FedeIlLeone commented on src/renderer/coremods/commands/index.ts
> +type commandState =
```suggestion
type CommandState =
```
A general convention in TypeScript is to use PascalCase for types/interfaces. Also replace the name below.

2024-04-07 20:04 UTC, FedeIlLeone approved these changes

2024-04-07 20:05 UTC, merged