Fixed coremods badges
replugged-org/replugged pull request #609
Opened 2024-04-03 03:04 UTC by zrodevkaan

2024-04-04 03:37 UTC, zrodevkaan commented
I FIXED LINT. YIPPEEEEEEEEEEE

2024-04-09 14:33 UTC, 12944qwerty requested changes

2024-04-09 14:33 UTC, 12944qwerty commented on src/renderer/coremods/badges/index.tsx
> +      const { children } = res.props.children.props;
use findInTree for this too. can't have it break on us again

2024-06-02 09:02 UTC, FedeIlLeone commented
Closing in favor of #623

2024-06-02 09:02 UTC, closed without merging