Fix enabling experiments
replugged-org/replugged pull request #68
Opened 2022-08-09 05:51 UTC by FifiTheBulldog

Fix the Discord experiments toggle. (Thank you Beef, I used the marked-up snippet here.) The only catch is that disabling experiments only sets the setting; it doesn’t actually disable them until the user reloads.

2022-08-09 08:29 UTC, lexisother requested changes

2022-08-09 08:29 UTC, lexisother commented on src/Powercord/plugins/pc-settings/experiments.js
> +}
Consider showing users a modal with info about a required reload before experiments are fully disabled.

2022-08-10 09:16 UTC, lleyton approved these changes
nya

2022-08-10 09:16 UTC, merged

2022-08-10 10:17 UTC, MichaelDavidGK commented
![image](https://user-images.githubusercontent.com/39009683/183877386-de47adb9-987e-4df1-a19d-10f32c0621c7.png)
Discord crashes

2022-08-10 10:19 UTC, thennothinghappened commented
what did you do to cause this?

2022-08-10 10:20 UTC, MichaelDavidGK commented
> what did you do to cause this?

just updated to latest which required reload

2022-08-10 10:22 UTC, thennothinghappened commented
not happening for me. I'll have a look but it's most likely one of your plugins

2022-08-10 10:28 UTC, thennothinghappened commented
hmm, not really sure what's going on. that's wrapped in a try catch and is supposed to error silently so it shouldn't be killing it.

2022-08-10 10:34 UTC, MichaelDavidGK commented
> not happening for me. I'll have a look but it's most likely one of your plugins

I'm removing all plugins and will be adding one by one to see if that's the issue, will take me a while cause I'm busy with something else rn (15 minutes?)

2022-08-10 11:22 UTC, MichaelDavidGK commented
Apparently it's PluginRepo from BD crashing it even tho nothing changed except Replugged update, welp I will live without it tbf

2022-08-10 11:45 UTC, thennothinghappened commented
weird, but good that's all cleared up now!

2022-08-10 12:36 UTC, asportnoy commented
Reverted this since it caused some issues and didn't work properly for everyone