Only show updates if manifest version was updated
replugged-org/replugged pull request #96
Opened 2022-08-11 11:36 UTC by elementemerald

Closes #89

2022-08-12 04:25 UTC, asportnoy commented
Still need to test/review this, but **do not merge this yet**. We need to announce to developers and give them sufficient notice. You can still test and review though.

2022-08-14 14:33 UTC, asportnoy requested changes
Small issue

2022-08-14 14:33 UTC, asportnoy commented on src/fake_node_modules/powercord/entities/Updatable.js
> +        const gitManifest = await PowercordNative.exec(`git show ${latest[0].id}:manifest.json`, {
Themes use `powercord_manifest.json` (same JSON key)

2022-08-14 20:53 UTC, asportnoy requested changes
I think having the same code repeated twice like this isn't ideal. Maybe move it back to updatable and add either use `entity instanceof Plugin` or add a `type` property to each to determine which file to use.

2022-08-14 21:45 UTC, asportnoy requested changes

2022-08-14 21:45 UTC, asportnoy commented on src/fake_node_modules/powercord/entities/Updatable.js
> +  constructor (basePath, entityType, entityID, updateIdentifier) {
Add this parameter to `src/Powercord/index.js#48`, otherwise LGTM

2022-08-14 21:51 UTC, asportnoy commented on src/Powercord/index.js
> +    super(join(__dirname, '..', '..'), '', 'plugin', 'powercord');
I think type `plugin` isn't appropriate here, maybe `base`?
```suggestion
    super(join(__dirname, '..', '..'), '', 'base', 'powercord');
```

2022-08-14 21:53 UTC, asportnoy approved these changes

2022-08-14 21:53 UTC, asportnoy commented
Will give notice in Discord and merge in a few days

2022-08-14 23:32 UTC, lexisother approved these changes
Yop.

2022-08-17 00:00 UTC, merged